//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgent
    {
        public string agentID { get; set; }
        public string agentName { get; set; }
        public string phoneNum { get; set; }
        public string agentAdress { get; set; }
        public string agentPass { get; set; }
    }
}
