//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillDetail
    {
        public int id { get; set; }
        public string goodID { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<double> unitSold { get; set; }
        public Nullable<double> billAmount { get; set; }
    
        public virtual tblGoodRecieve tblGoodRecieve { get; set; }
    }
}
