//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillDetail
    {
        public string greID { get; set; }
        public string goodID { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public Nullable<double> totalBill { get; set; }
        public string billstatus { get; set; }
    }
}
