//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public string empID { get; set; }
        public string empName { get; set; }
        public string empPhonenum { get; set; }
        public string empPass { get; set; }
    }
}
