//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGoodRecieve
    {
        public string greID { get; set; }
        public string empID { get; set; }
        public string agentID { get; set; }
        public System.DateTime sellDate { get; set; }
        public Nullable<double> greTotal { get; set; }
    }
}
