//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGood
    {
        public string goodID { get; set; }
        public string goodName { get; set; }
        public string cateID { get; set; }
        public Nullable<double> goodAmount { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public Nullable<double> unitSold { get; set; }
        public string note { get; set; }
    }
}
